/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Account': { kind: 'OBJECT'; name: 'Account'; fields: { 'accountInfo': { name: 'accountInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AccountInfo'; ofType: null; }; } }; 'apps': { name: 'apps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppsConnection'; ofType: null; }; } }; 'checkout': { name: 'checkout'; type: { kind: 'OBJECT'; name: 'Checkout'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'stores': { name: 'stores'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StoreConnection'; ofType: null; }; } }; 'subscriptions': { name: 'subscriptions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SubscriptionConnection'; ofType: null; }; } }; 'users': { name: 'users'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserConnection'; ofType: null; }; } }; }; };
    'AccountInfo': { kind: 'OBJECT'; name: 'AccountInfo'; fields: { 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'AccountMutations': { kind: 'OBJECT'; name: 'AccountMutations'; fields: { 'addUserToAccount': { name: 'addUserToAccount'; type: { kind: 'OBJECT'; name: 'AddUserToAccountResult'; ofType: null; } }; 'removeUserFromAccount': { name: 'removeUserFromAccount'; type: { kind: 'OBJECT'; name: 'RemoveUserFromAccountResult'; ofType: null; } }; }; };
    'AddUserToAccountInput': { kind: 'INPUT_OBJECT'; name: 'AddUserToAccountInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'AddUserToAccountResult': { kind: 'OBJECT'; name: 'AddUserToAccountResult'; fields: { 'account': { name: 'account'; type: { kind: 'OBJECT'; name: 'Account'; ofType: null; } }; }; };
    'AddUserToStoreInput': { kind: 'INPUT_OBJECT'; name: 'AddUserToStoreInput'; isOneOf: false; inputFields: [{ name: 'storeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UserIdentifierInput'; ofType: null; }; }; defaultValue: null }]; };
    'AddUserToStoreResult': { kind: 'OBJECT'; name: 'AddUserToStoreResult'; fields: { 'storeId': { name: 'storeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'App': { kind: 'OBJECT'; name: 'App'; fields: { 'eventSources': { name: 'eventSources'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AwsEventSourcesConnection'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'AppMutations': { kind: 'OBJECT'; name: 'AppMutations'; fields: { 'createEventSource': { name: 'createEventSource'; type: { kind: 'OBJECT'; name: 'CreateEventSourceResult'; ofType: null; } }; 'deleteEventSource': { name: 'deleteEventSource'; type: { kind: 'OBJECT'; name: 'DeleteEventSourceResult'; ofType: null; } }; }; };
    'AppsConnection': { kind: 'OBJECT'; name: 'AppsConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'AppsEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'AppsEdge': { kind: 'OBJECT'; name: 'AppsEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'App'; ofType: null; }; } }; }; };
    'AwsEventSource': { kind: 'OBJECT'; name: 'AwsEventSource'; fields: { 'arn': { name: 'arn'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'awsAccount': { name: 'awsAccount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'eventSourceName': { name: 'eventSourceName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'eventSourceRegion': { name: 'eventSourceRegion'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AwsRegion'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'webhooksCount': { name: 'webhooksCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Long'; ofType: null; }; } }; }; };
    'AwsEventSourcesConnection': { kind: 'OBJECT'; name: 'AwsEventSourcesConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'AwsEventSourcesEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'AwsEventSourcesEdge': { kind: 'OBJECT'; name: 'AwsEventSourcesEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AwsEventSource'; ofType: null; }; } }; }; };
    'AwsRegion': { name: 'AwsRegion'; enumValues: 'AF_SOUTH_1' | 'AP_EAST_1' | 'AP_NORTHEAST_1' | 'AP_NORTHEAST_2' | 'AP_NORTHEAST_3' | 'AP_SOUTHEAST_1' | 'AP_SOUTHEAST_2' | 'AP_SOUTHEAST_3' | 'AP_SOUTHEAST_4' | 'AP_SOUTH_1' | 'AP_SOUTH_2' | 'CA_CENTRAL_1' | 'EU_CENTRAL_1' | 'EU_CENTRAL_2' | 'EU_NORTH_1' | 'EU_SOUTH_1' | 'EU_SOUTH_2' | 'EU_WEST_1' | 'EU_WEST_2' | 'EU_WEST_3' | 'IL_CENTRAL_1' | 'ME_CENTRAL_1' | 'SA_EAST_1' | 'US_EAST_1' | 'US_EAST_2' | 'US_WEST_1' | 'US_WEST_2'; };
    'BigDecimal': unknown;
    'Boolean': unknown;
    'CancelSubscriptionInput': { kind: 'INPUT_OBJECT'; name: 'CancelSubscriptionInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'CancelSubscriptionResult': { kind: 'OBJECT'; name: 'CancelSubscriptionResult'; fields: { 'cancelledAt': { name: 'cancelledAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'subscriptionId': { name: 'subscriptionId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'Checkout': { kind: 'OBJECT'; name: 'Checkout'; fields: { 'accountId': { name: 'accountId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'checkoutUrl': { name: 'checkoutUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItemConnection'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'CheckoutStatus'; ofType: null; } }; }; };
    'CheckoutItem': { kind: 'OBJECT'; name: 'CheckoutItem'; fields: { 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'pricingPlan': { name: 'pricingPlan'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItemPricingPlan'; ofType: null; }; } }; 'product': { name: 'product'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItemProduct'; ofType: null; }; } }; 'redirectUrl': { name: 'redirectUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'scope': { name: 'scope'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItemScope'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'CheckoutItemStatus'; ofType: null; } }; 'subscriptionId': { name: 'subscriptionId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'CheckoutItemConnection': { kind: 'OBJECT'; name: 'CheckoutItemConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItemEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'CheckoutItemEdge': { kind: 'OBJECT'; name: 'CheckoutItemEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutItem'; ofType: null; }; } }; }; };
    'CheckoutItemInput': { kind: 'INPUT_OBJECT'; name: 'CheckoutItemInput'; isOneOf: false; inputFields: [{ name: 'description'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'pricingPlan'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'PricingPlanInput'; ofType: null; }; }; defaultValue: null }, { name: 'product'; type: { kind: 'INPUT_OBJECT'; name: 'CheckoutItemProductInput'; ofType: null; }; defaultValue: null }, { name: 'redirectUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'scope'; type: { kind: 'INPUT_OBJECT'; name: 'CheckoutItemScopeInput'; ofType: null; }; defaultValue: null }, { name: 'subscriptionId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'CheckoutItemPricingInterval': { name: 'CheckoutItemPricingInterval'; enumValues: 'ANNUAL' | 'MONTH' | 'ONCE' | 'QUARTER' | 'SEMIANNUAL'; };
    'CheckoutItemPricingPlan': { kind: 'OBJECT'; name: 'CheckoutItemPricingPlan'; fields: { 'interval': { name: 'interval'; type: { kind: 'ENUM'; name: 'CheckoutItemPricingInterval'; ofType: null; } }; 'price': { name: 'price'; type: { kind: 'OBJECT'; name: 'Money'; ofType: null; } }; 'trialDays': { name: 'trialDays'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'CheckoutItemProduct': { kind: 'OBJECT'; name: 'CheckoutItemProduct'; fields: { 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'productLevel': { name: 'productLevel'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'ENUM'; name: 'CheckoutItemProductType'; ofType: null; } }; }; };
    'CheckoutItemProductInput': { kind: 'INPUT_OBJECT'; name: 'CheckoutItemProductInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'productLevel'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'CheckoutItemProductType'; ofType: null; }; defaultValue: null }]; };
    'CheckoutItemProductType': { name: 'CheckoutItemProductType'; enumValues: 'APPLICATION'; };
    'CheckoutItemScope': { kind: 'OBJECT'; name: 'CheckoutItemScope'; fields: { 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'type': { name: 'type'; type: { kind: 'ENUM'; name: 'CheckoutItemScopeType'; ofType: null; } }; }; };
    'CheckoutItemScopeInput': { kind: 'INPUT_OBJECT'; name: 'CheckoutItemScopeInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'CheckoutItemScopeType'; ofType: null; }; defaultValue: null }]; };
    'CheckoutItemScopeType': { name: 'CheckoutItemScopeType'; enumValues: 'STORE'; };
    'CheckoutItemStatus': { name: 'CheckoutItemStatus'; enumValues: 'COMPLETE' | 'PENDING' | 'PROCESSING'; };
    'CheckoutMutations': { kind: 'OBJECT'; name: 'CheckoutMutations'; fields: { 'createCheckout': { name: 'createCheckout'; type: { kind: 'OBJECT'; name: 'CreateCheckoutResult'; ofType: null; } }; }; };
    'CheckoutStatus': { name: 'CheckoutStatus'; enumValues: 'COMPLETE' | 'PENDING' | 'PROCESSING'; };
    'CollectionInfo': { kind: 'OBJECT'; name: 'CollectionInfo'; fields: { 'totalItems': { name: 'totalItems'; type: { kind: 'SCALAR'; name: 'Long'; ofType: null; } }; }; };
    'CreateCheckoutInput': { kind: 'INPUT_OBJECT'; name: 'CreateCheckoutInput'; isOneOf: false; inputFields: [{ name: 'accountId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CheckoutItemInput'; ofType: null; }; }; }; }; defaultValue: null }]; };
    'CreateCheckoutResult': { kind: 'OBJECT'; name: 'CreateCheckoutResult'; fields: { 'checkout': { name: 'checkout'; type: { kind: 'OBJECT'; name: 'Checkout'; ofType: null; } }; }; };
    'CreateEventSourceInput': { kind: 'INPUT_OBJECT'; name: 'CreateEventSourceInput'; isOneOf: false; inputFields: [{ name: 'appId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'awsAccount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'eventSourceName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'eventSourceRegion'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AwsRegion'; ofType: null; }; }; defaultValue: null }]; };
    'CreateEventSourceResult': { kind: 'OBJECT'; name: 'CreateEventSourceResult'; fields: { 'eventSource': { name: 'eventSource'; type: { kind: 'OBJECT'; name: 'AwsEventSource'; ofType: null; } }; }; };
    'CreateUserInput': { kind: 'INPUT_OBJECT'; name: 'CreateUserInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'firstName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'lastName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'CreateUserResult': { kind: 'OBJECT'; name: 'CreateUserResult'; fields: { 'user': { name: 'user'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'CreateUserWithPasswordInput': { kind: 'INPUT_OBJECT'; name: 'CreateUserWithPasswordInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'firstName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'lastName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'password'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'passwordConfirmation'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'CreateUserWithPasswordResult': { kind: 'OBJECT'; name: 'CreateUserWithPasswordResult'; fields: { 'user': { name: 'user'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'CurrencyCode': { name: 'CurrencyCode'; enumValues: 'AED' | 'AFN' | 'ALL' | 'AMD' | 'ANG' | 'AOA' | 'ARS' | 'AUD' | 'AWG' | 'AZN' | 'BAM' | 'BBD' | 'BDT' | 'BGN' | 'BHD' | 'BIF' | 'BMD' | 'BND' | 'BOB' | 'BOV' | 'BRL' | 'BSD' | 'BTN' | 'BWP' | 'BYN' | 'BYR' | 'BZD' | 'CAD' | 'CDF' | 'CHE' | 'CHF' | 'CHW' | 'CLF' | 'CLP' | 'CNY' | 'COP' | 'COU' | 'CRC' | 'CUC' | 'CUP' | 'CVE' | 'CZK' | 'DJF' | 'DKK' | 'DOP' | 'DZD' | 'EGP' | 'ERN' | 'ETB' | 'EUR' | 'FJD' | 'FKP' | 'GBP' | 'GEL' | 'GHS' | 'GIP' | 'GMD' | 'GNF' | 'GTQ' | 'GYD' | 'HKD' | 'HNL' | 'HRK' | 'HTG' | 'HUF' | 'IDR' | 'ILS' | 'INR' | 'IQD' | 'IRR' | 'ISK' | 'JMD' | 'JOD' | 'JPY' | 'KES' | 'KGS' | 'KHR' | 'KMF' | 'KPW' | 'KRW' | 'KWD' | 'KYD' | 'KZT' | 'LAK' | 'LBP' | 'LKR' | 'LRD' | 'LSL' | 'LYD' | 'MAD' | 'MDL' | 'MGA' | 'MKD' | 'MMK' | 'MNT' | 'MOP' | 'MRO' | 'MRU' | 'MUR' | 'MVR' | 'MWK' | 'MXN' | 'MYR' | 'MZN' | 'NAD' | 'NGN' | 'NIO' | 'NOK' | 'NPR' | 'NZD' | 'OMR' | 'PAB' | 'PEN' | 'PGK' | 'PHP' | 'PKR' | 'PLN' | 'PYG' | 'QAR' | 'RON' | 'RSD' | 'RUB' | 'RWF' | 'SAR' | 'SBD' | 'SCR' | 'SDG' | 'SEK' | 'SGD' | 'SHP' | 'SLL' | 'SOS' | 'SRD' | 'SSP' | 'STD' | 'STN' | 'SVC' | 'SYP' | 'SZL' | 'THB' | 'TJS' | 'TMT' | 'TND' | 'TOP' | 'TRY' | 'TTD' | 'TWD' | 'TZS' | 'UAH' | 'UGX' | 'USD' | 'USN' | 'UYI' | 'UYU' | 'UZS' | 'VEF' | 'VES' | 'VND' | 'VUV' | 'WST' | 'XAF' | 'XAG' | 'XAU' | 'XBA' | 'XBB' | 'XBC' | 'XBD' | 'XCD' | 'XDR' | 'XOF' | 'XPD' | 'XPF' | 'XPT' | 'XSU' | 'XTS' | 'XUA' | 'XXX' | 'YER' | 'ZAR' | 'ZMW' | 'ZWL'; };
    'DateTime': unknown;
    'DeleteEventSourceInput': { kind: 'INPUT_OBJECT'; name: 'DeleteEventSourceInput'; isOneOf: false; inputFields: [{ name: 'appId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'DeleteEventSourceResult': { kind: 'OBJECT'; name: 'DeleteEventSourceResult'; fields: { 'affectedWebhooksIds': { name: 'affectedWebhooksIds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; }; } }; 'deletedEventSourceId': { name: 'deletedEventSourceId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'ID': unknown;
    'Int': unknown;
    'Long': unknown;
    'Money': { kind: 'OBJECT'; name: 'Money'; fields: { 'currencyCode': { name: 'currencyCode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigDecimal'; ofType: null; }; } }; }; };
    'MoneyInput': { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; isOneOf: false; inputFields: [{ name: 'currencyCode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'CurrencyCode'; ofType: null; }; }; defaultValue: null }, { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigDecimal'; ofType: null; }; }; defaultValue: null }]; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'account': { name: 'account'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AccountMutations'; ofType: null; }; } }; 'app': { name: 'app'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppMutations'; ofType: null; }; } }; 'checkout': { name: 'checkout'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CheckoutMutations'; ofType: null; }; } }; 'subscription': { name: 'subscription'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SubscriptionMutations'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserMutations'; ofType: null; }; } }; }; };
    'Node': { kind: 'INTERFACE'; name: 'Node'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; possibleTypes: 'Checkout' | 'Subscription'; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'PricingPlanInput': { kind: 'INPUT_OBJECT'; name: 'PricingPlanInput'; isOneOf: false; inputFields: [{ name: 'interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'CheckoutItemPricingInterval'; ofType: null; }; }; defaultValue: null }, { name: 'price'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; ofType: null; }; }; defaultValue: null }, { name: 'trialDays'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }]; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'account': { name: 'account'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'INTERFACE'; name: 'Node'; ofType: null; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'INTERFACE'; name: 'Node'; ofType: null; }; }; } }; 'system': { name: 'system'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'System'; ofType: null; }; } }; }; };
    'RemoveUserFromAccountInput': { kind: 'INPUT_OBJECT'; name: 'RemoveUserFromAccountInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'userId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'RemoveUserFromAccountResult': { kind: 'OBJECT'; name: 'RemoveUserFromAccountResult'; fields: { 'accountId': { name: 'accountId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'RemoveUserFromStoreInput': { kind: 'INPUT_OBJECT'; name: 'RemoveUserFromStoreInput'; isOneOf: false; inputFields: [{ name: 'storeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'RemoveUserFromStoreResult': { kind: 'OBJECT'; name: 'RemoveUserFromStoreResult'; fields: { 'storeId': { name: 'storeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'Store': { kind: 'OBJECT'; name: 'Store'; fields: { 'apps': { name: 'apps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppsConnection'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'storeHash': { name: 'storeHash'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'users': { name: 'users'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StoreUserConnection'; ofType: null; }; } }; }; };
    'StoreConnection': { kind: 'OBJECT'; name: 'StoreConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'StoreEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'StoreEdge': { kind: 'OBJECT'; name: 'StoreEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Store'; ofType: null; }; } }; }; };
    'StoreFilterInput': { kind: 'INPUT_OBJECT'; name: 'StoreFilterInput'; isOneOf: false; inputFields: [{ name: 'ids'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; }; defaultValue: null }, { name: 'storeHashes'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }]; };
    'StoreUser': { kind: 'OBJECT'; name: 'StoreUser'; fields: { 'apps': { name: 'apps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppsConnection'; ofType: null; }; } }; 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'firstName': { name: 'firstName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'lastLoginAt': { name: 'lastLoginAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'lastName': { name: 'lastName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'permissions': { name: 'permissions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'StoreUserStatus'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; }; };
    'StoreUserConnection': { kind: 'OBJECT'; name: 'StoreUserConnection'; fields: { 'collectionInfo': { name: 'collectionInfo'; type: { kind: 'OBJECT'; name: 'CollectionInfo'; ofType: null; } }; 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'StoreUserEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'StoreUserEdge': { kind: 'OBJECT'; name: 'StoreUserEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StoreUser'; ofType: null; }; } }; }; };
    'StoreUserStatus': { name: 'StoreUserStatus'; enumValues: 'ACTIVE' | 'INACTIVE'; };
    'String': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'accountId': { name: 'accountId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'activationDate': { name: 'activationDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'billingInterval': { name: 'billingInterval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'SubscriptionBillingInterval'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'currentPeriodEnd': { name: 'currentPeriodEnd'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'pricePerInterval': { name: 'pricePerInterval'; type: { kind: 'OBJECT'; name: 'Money'; ofType: null; } }; 'product': { name: 'product'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SubscriptionProduct'; ofType: null; }; } }; 'scope': { name: 'scope'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SubscriptionScope'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'SubscriptionStatus'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'SubscriptionBillingInterval': { name: 'SubscriptionBillingInterval'; enumValues: 'ANNUAL' | 'MONTH' | 'NONE' | 'ONCE' | 'QUARTER' | 'SEMIANNUAL'; };
    'SubscriptionConnection': { kind: 'OBJECT'; name: 'SubscriptionConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'SubscriptionEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'SubscriptionEdge': { kind: 'OBJECT'; name: 'SubscriptionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Subscription'; ofType: null; }; } }; }; };
    'SubscriptionFiltersInput': { kind: 'INPUT_OBJECT'; name: 'SubscriptionFiltersInput'; isOneOf: false; inputFields: [{ name: 'ids'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; }; defaultValue: null }, { name: 'productId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'productType'; type: { kind: 'ENUM'; name: 'SubscriptionProductType'; ofType: null; }; defaultValue: null }, { name: 'scopeId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'scopeType'; type: { kind: 'ENUM'; name: 'SubscriptionScopeType'; ofType: null; }; defaultValue: null }, { name: 'status'; type: { kind: 'ENUM'; name: 'SubscriptionStatus'; ofType: null; }; defaultValue: null }, { name: 'updatedAfter'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }]; };
    'SubscriptionMutations': { kind: 'OBJECT'; name: 'SubscriptionMutations'; fields: { 'cancelSubscription': { name: 'cancelSubscription'; type: { kind: 'OBJECT'; name: 'CancelSubscriptionResult'; ofType: null; } }; }; };
    'SubscriptionProduct': { kind: 'OBJECT'; name: 'SubscriptionProduct'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'productLevel': { name: 'productLevel'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'ENUM'; name: 'SubscriptionProductType'; ofType: null; } }; }; };
    'SubscriptionProductType': { name: 'SubscriptionProductType'; enumValues: 'APPLICATION' | 'NONE'; };
    'SubscriptionScope': { kind: 'OBJECT'; name: 'SubscriptionScope'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'ENUM'; name: 'SubscriptionScopeType'; ofType: null; } }; }; };
    'SubscriptionScopeType': { name: 'SubscriptionScopeType'; enumValues: 'STORE'; };
    'SubscriptionStatus': { name: 'SubscriptionStatus'; enumValues: 'ACTIVE' | 'CANCELLED' | 'SUSPENDED'; };
    'System': { kind: 'OBJECT'; name: 'System'; fields: { 'time': { name: 'time'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Long'; ofType: null; }; } }; }; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'firstName': { name: 'firstName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'lastName': { name: 'lastName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'locale': { name: 'locale'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'UserConnection': { kind: 'OBJECT'; name: 'UserConnection'; fields: { 'collectionInfo': { name: 'collectionInfo'; type: { kind: 'OBJECT'; name: 'CollectionInfo'; ofType: null; } }; 'edges': { name: 'edges'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'UserEdge'; ofType: null; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'UserEdge': { kind: 'OBJECT'; name: 'UserEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'UserIdentifierInput': { kind: 'INPUT_OBJECT'; name: 'UserIdentifierInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'UserMutations': { kind: 'OBJECT'; name: 'UserMutations'; fields: { 'addUserToStore': { name: 'addUserToStore'; type: { kind: 'OBJECT'; name: 'AddUserToStoreResult'; ofType: null; } }; 'createUser': { name: 'createUser'; type: { kind: 'OBJECT'; name: 'CreateUserResult'; ofType: null; } }; 'createUserWithPassword': { name: 'createUserWithPassword'; type: { kind: 'OBJECT'; name: 'CreateUserWithPasswordResult'; ofType: null; } }; 'removeUserFromStore': { name: 'removeUserFromStore'; type: { kind: 'OBJECT'; name: 'RemoveUserFromStoreResult'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}
